config/routes.rb
Rails.application.routes.draw do
  # User authentication
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, except: [ :show ]
  resources :category_groups, except: [ :index, :show ]
  resources :accounts, except: [ :show ]
  resources :transactions, except: [ :show ]
  # resources :budgets, only: [ :index ]

  get "budgets" => "budgets#index", as: :budgets
  get "budgets/:date" => "budgets#index", as: :budgets_month

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/budgets")
  root "transactions#index"
end

app/models/budget.rb
class Budget < ApplicationRecord
  has_many :budget_categories, dependent: :destroy

  def month_name
    Date::ABBR_MONTHNAMES[self.month]
  end

  def month_year
    [ format("%02d", month), year.to_s ]
  end

  def remaining_to_assign
    (income || 0) - (assigned || 0)
  end

  def create_budget_categories
    return unless budget_categories.empty?
    Category.where(is_income: false).each do |category|
      budget_categories.build(
        category: category,
        starting_amount: 0.00,
        assigned_amount: 0.00,
        required_amount: 0.00,
        spent_amount: 0.00
      )
    end
  end

  def update_categories
    budget_categories.each do |budget_category|
      budget_category.update_category(budget_category.category)
    end
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :resume_session
  before_action :get_dates, only: [ :index ]

  # GET /budgets or /budgets.json
  def index
    # Get the budget for the current month and year
    @budget = Budget.find_by(month: @month, year: @year)
    # If the budget doesn't exist, create a new one
    @budget = BudgetService.new.find_or_create_budget(@month, @year) unless @budget
    @budget_categories = BudgetCategory.left_outer_joins(:category)
                                   .where(budget_id: @budget.id)
                                   .where('categories.is_income = ?', false)
                                   .order('categories.name ASC')

  end

  private

  def budget_params
    params.require(:budget).permit(:month, :year, :amount)
  end

  def get_dates
    if params[:date].present?
      @year = params[:date].scan(/\d{4}/).first.to_i
      @month = params[:date].scan(/\d{2}/).last.to_i
    else
      @month = params[:month]&.to_i || Date.today.month
      @year = params[:year]&.to_i || Date.today.year
    end

    # Calculate the previous and next months
    current_date = Date.new(@year, @month, 1)
    @prev_date = "%02d" % current_date.prev_month.year + "%02d" % current_date.prev_month.month
    @next_date = "%02d" % current_date.next_month.year + "%02d" % current_date.next_month.month
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Month:</strong>
    <%= budget.month %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Year:</strong>
    <%= budget.year %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Income:</strong>
    <%= budget.income %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Assigned:</strong>
    <%= budget.assigned %>
  </p>

</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget_category, data: { turbo: false }) do |form| %>
  <% if budget_category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(budget_category.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :assigned_amount %>
    <%= form.text_field :assigned_amount, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/budgets/_list.html.erb
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
  <% @budgets.each do |budget| %>
    <%= render budget %>
  <% end %>
</div>

app/views/budgets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing budget</h1>

  <%= render "form", budget: @budget %>

  <%= link_to "Show this budget", @budget, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to budgets", budgets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/budgets/index.html.erb
<div class="w-full">
  <div class="grid grid-cols-3 text-center pb-2">
    <div>
      <%= link_to "Previous",
      budgets_month_path(date: @prev_date),
      class:
        "rounded py-1 px-5 text-white text-center dark:text-black bg-teal-500 hover:bg-teal-600 no-underline inline-block font-medium" %>
    </div>
    <div class="py-1 px-5 font-medium text-lg">
      <%= @budget.month_name %>
      <%= @budget.year %>
    </div>
    <div>
      <%= link_to "Next",
      budgets_month_path(date: @next_date),
      class:
        "rounded py-1 px-5 text-white text-center dark:text-black bg-teal-500 hover:bg-teal-600 no-underline inline-block font-medium" %>
    </div>
  </div>
  <div class="text-center mx-auto pb-2">
    Remaining To Assign: <%= number_to_currency(@budget.remaining_to_assign) %>
  </div>
  <div class="tgrid-container">
    <div class="grid grid-cols-4 tgrid-header">
      <div class="tgrid-header-column">
        Category
      </div>
      <div class="tgrid-header-column">
        Budget
      </div>
      <div class="tgrid-header-column">
        Spent
      </div>
      <div class="tgrid-header-column">
        Remain
      </div>
    </div>
    <% @budget.budget_categories.each { |budget_category| %>
    <div class="grid grid-cols-4 gap-8 tgrid-row">
      <div class="font-medium text-left ml-2">
        <%= budget_category.category.name %>
      </div>
      <div class="font-medium text-center">
        <%= number_to_currency(budget_category.required_amount) %>
      </div>
      <div class="font-medium text-center">
        <%= number_to_currency(budget_category.spent_amount) %>
      </div>
      <div class="font-medium mr-2 currency-indicator-<%= budget_category.remaining_amount <= 0 ? 'danger' : 'positive-strong' %>">
        <%= number_to_currency(budget_category.remaining_amount) %>
      </div>
    </div>
    <% } %>
  </div>
</div>

app/views/budgets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New budget</h1>

  <%= render "form", budget: @budget %>

  <%= link_to "Back to budgets", budgets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/budgets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @budget %>

    <%= link_to "Edit this budget", edit_budget_path(@budget), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to budgets", budgets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this budget", @budget, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>