config/routes.rb
Rails.application.routes.draw do
  # User authentication
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, except: [ :show ]
  resources :category_groups, except: [ :index, :show ]
  resources :accounts, except: [ :show ]
  resources :transactions, except: [ :show ]
  # resources :budgets, only: [ :index ]

  get "budgets" => "budgets#index", as: :budgets
  get "budgets/:date" => "budgets#index", as: :budgets_month

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/budgets")
  root "transactions#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category_group
  has_many :transactions

  def can_delete?
    !category_group.is_income? || category_group.categories.count > 1
  end

  def sum_transactions_for_budget(budget)
    transactions.where(
      "to_char(entry, 'MM') = ? AND to_char(entry, 'YYYY') = ?",
      *budget.month_year
    )
    .sum(:amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :resume_session
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @category_groups = CategoryGroup.left_outer_joins(:categories).order(is_income: :desc, name: :asc).distinct
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category.category_group_id = params[:category_group_id] if params[:category_group_id].present?
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.is_income = @category.category_group.is_income?

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category.is_income = @category.category_group.is_income?
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :category_group_id ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="grid grid-cols-2 tgrid-row">
  <div class="text-start pl-8">
    <%= category.name %>
  </div>
  <div class="tgrid-row-actions-end">
    <%= edit_button edit_category_path(category) %>
    <%= delete_button(category) if category.can_delete? %>
  </div>
</div>

app/views/categories/_empty.html.erb
<div class="text-center grid grid-cols-1 tgrid-row">
  No categories found
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, data: { turbo: false }) do |form| %>
  <%= form_errors category %>

  <div class="my-5">
    <%= form.label :category_group %>
    <%= form.collection_select :category_group_id,
                           CategoryGroup.all,
                           :id,
                           :name,
                           { include_blank: false },
                           class:
                             "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
                    class:
                      "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex space-x-3 items-center justify-between">
    <%= submit_button form %>
    <%= cancel_button categories_path %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl">

        <h1 id="modal-title" class="dark:text-slate-100">Edit Category</h1>
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="w-full">
  <% content_for :title, "Categories" %>

  <div class="grid grid-cols-1 mb-4">
    <div class="text-left text-2xl font-bold pl-2 pt-2">Categories by Group</div>
  </div>

  <div id="categories" class="tgrid-container pb-4">
    <% @category_groups.each do |category_group| %>
      <div class="grid grid-cols-2 tgrid-header text-start pl-2">
        <div>
          <h2 class="font-bold text-2xl"><%= category_group.name %></h2>
        </div>
        <div class="tgrid-row-actions-end">
          <%= link_to "New Category", new_category_path(category_group_id: category_group.id), class: "btn-primary" %>
          <% unless category_group.is_income? %>
            <%= button_to "Delete Group", category_group, data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn-danger" %>
          <% end %>
        </div>
      </div>
      <%= render(category_group.categories) || render('empty') %>
      <% if category_group.is_income %>
        <div class="box-content m-auto h-2 p-4 bg-slate-100 dark:bg-slate-800"><hr/></div>
        <div class="grid grid-cols-2 py-2">
          <div class="text-start font-bold text-black dark:text-white pt-4">Expenses</div>
          <div class="text-right pr-2 pt-2"><%= link_to "New Category Group", new_category_group_path, class: "btn-primary" %></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<%= turbo_frame_tag "model" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl">

        <h1 id="modal-title" class="dark:text-slate-100">New Category</h1>
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this category", @category, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>