config/routes.rb
Rails.application.routes.draw do
  # User authentication
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, except: [ :show ]
  resources :category_groups, except: [ :index, :show ]
  resources :accounts, except: [ :show ]
  resources :transactions, except: [ :show ]
  # resources :budgets, only: [ :index ]

  get "budgets" => "budgets#index", as: :budgets
  get "budgets/:date" => "budgets#index", as: :budgets_month

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/budgets")
  root "transactions#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :resume_session
  before_action :set_transaction, only: %i[ edit update destroy ]
  helper_method :sort_column, :sort_direction

  # GET /transactions or /transactions.json
  def index
    @selected_account_id = params[:account_id]&.to_i || 0
    query = Transaction.order(sort_column => sort_direction).for_account(@selected_account_id)
    @pagy, @transactions = pagy(query)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.entry = Date.today
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = TransactionService.create_transaction(transaction_params[:transaction])

    respond_to do |format|
      if @transaction
        format.html { redirect_to transactions_path, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_path, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_path, status: :see_other, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.expect(transaction: [ :entry, :description, :amount, :account_id, :category_id ])
    end

    def sort_column
      Transaction.column_names.include?(params[:sort]) ? params[:sort] : "entry"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, data: { turbo: false }) do |form| %>
  <%= form_errors transaction %>

  <div class="my-5">
    <%= form.label :account %>
    <%= form.collection_select :account_id, Account.all, :id, :name, { include_blank: false }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full dark:text-black" %>
  </div>

  <div class="my-5">
    <%= form.label :entry %>
    <%= form.date_field :entry, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.grouped_collection_select :category_id, CategoryGroup.all, :categories, :name, :id, :name, { include_blank: false }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex space-x-3 items-center justify-between">
    <%= submit_button form %>
    <%= cancel_button transactions_path %>
  </div>
<% end %>

app/views/transactions/_list.html.erb
<% @transactions.each do |transaction| %>
  <%= render transaction %>
  <p>
    <%= link_to "Edit", edit_transaction_path(transaction), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= button_to "Destroy", transaction, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </p>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="grid <%= @selected_account.blank? ? "grid-cols-6" : "grid-cols-5" %> tgrid-row">
  <% if @selected_account.blank? %>
  <div>
    <%= transaction.account.name %>
  </div>
  <% end %>
  <div>
    <%= transaction.entry.strftime("%b %d, %Y") %>
  </div>
  <div class="text-left">
    <%= transaction.category.category_group.name %>: <%= transaction.category.name %>
  </div>
  <div class="text-left">
    <%= transaction.description %>
  </div>
  <div class="<%= transaction.amount < 0 ? 'text-red-600' : 'text-green-600' %>">
    <%= number_to_currency(transaction.amount) %>
  </div>
  <div class="tgrid-row-actions">
    <%= edit_button edit_transaction_path(transaction) %>
    <%= delete_button transaction %>
  </div>
</div>

app/views/transactions/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto min-w-[600px] rounded-2xl">

        <h1 id="modal-title">Edit transaction</h1>
        <%= render "form", transaction: @transaction %>
      </div>
    </div>
  </div>
<% end %>

app/views/transactions/index.html.erb
<div class="w-full p-4">
  <% content_for :title, (@selected_account.present? ? @selected_account.name : "All") + " Transactions" %>

  <div class="grid grid-cols-2 mb-4">
    <div class="text-left text-2xl font-bold pl-2 pt-2">
      <%= (@selected_account.present? ? @selected_account.name : "All") %> Transactions
    </div>
    <div class="text-right pr-2 pt-2">
      <%= new_button new_transaction_path %>
    </div>
  </div>

  <div id="transactions" class="tgrid-container">
    <div class="grid <%= @selected_account.blank? ? "grid-cols-6" : "grid-cols-5" %> tgrid-header">
      <% if @selected_account.blank? %>
      <div>
        <strong class="tgrid-header-column">Account</strong>
      </div>
      <% end %>
      <div>
        <%= sortable "entry", "Entry", "tgrid-header-column" %>
      </div>
      <div>
        <strong class="tgrid-header-column">Category</strong>
      </div>
      <div>
        <strong class="tgrid-header-column">Description</strong>
      </div>
      <div>
        <%= sortable "amount", "Amount", "tgrid-header-column" %>
      </div>
      <div>
        <strong class="tgrid-header-column">Action</strong>
      </div>
    </div>
    <% @transactions.each do |transaction| %>
      <%= render transaction %>
    <% end %>
  </div>
  <div class="mb-5 p-4 flex justify-between">
    <div class="text-start"><%== pagy_info(@pagy) %></div>
    <div class="text-end justify-end"><%== pagy_nav(@pagy) %></div>
  </div>
</div>

app/views/transactions/new.html.erb
<%= turbo_frame_tag "model" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto min-w-[600px] rounded-2xl">

        <h1 id="modal-title">New transaction</h1>
        <%= render "form", transaction: @transaction %>
      </div>
    </div>
  </div>
<% end %>