config/routes.rb
Rails.application.routes.draw do
  # User authentication
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, except: [ :show ]
  resources :category_groups, except: [ :index, :show ]
  resources :accounts, except: [ :show ]
  resources :transactions, except: [ :show ]
  # resources :budgets, only: [ :index ]

  get "budgets" => "budgets#index", as: :budgets
  get "budgets/:date" => "budgets#index", as: :budgets_month

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/budgets")
  root "transactions#index"
end

app/models/account.rb
class Account < ApplicationRecord
  enum :account_type, [ :checking, :savings, :credit_card, :cash, :loan, :credit_line ]
  has_many :transactions, dependent: :destroy
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :resume_session
  before_action :set_account, only: %i[ edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    # @accounts is already loaded in ApplicationController
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_path, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_path, status: :see_other, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.expect(account: [ :name, :account_type, :budget, :credit ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>" class="grid grid-cols-5 tgrid-row">
  <div>
    <%= account.name %>
  </div>
  <div>
    <%= account.account_type.humanize %>
  </div>
  <div>
    <%= account.budget ? "Yes" : "No" %>
  </div>
  <div>
    <%= account.credit ? "Yes" : "No" %>
  </div>
  <div class="tgrid-row-actions">
    <%= edit_button edit_account_path(account) %>
    <%= delete_button account_path(account) %>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, data: { turbo: false }) do |form| %>
  <%= form_errors account %>

  <div class="mb-6">
    <%= form.label :name, class: "block mb-1" %>
    <%= form.text_field :name, class: "dark:text-black w-full rounded border border-slate-300 shadow-inner focus:ring-4 focus:ring-slate-50 text-base placeholder:text-slate-500 dark:placeholder:text-black focus:shadow-none focus:border-slate-400" %>
  </div>

  <div class="mb-6">
    <%= form.label :account_type, class: "block mb-1" %>
    <%= form.select :account_type,
                Account.account_types.keys.map { |w| [w.humanize, w] },
                {},
                class: "dark:text-black block shadow w-full rounded border border-slate-300 shadow-inner focus:ring-4 focus:ring-slate-50 text-base placeholder:text-slate-500 focus:shadow-none focus:border-slate-400" %>
  </div>

  <div class="mb-6">
    <label class="relative inline-flex items-center cursor-pointer">
      <%= form.check_box :budget, { class: "sr-only peer" }, checked_value = "1", unchecked_value = "0"  %>
      <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-green-300 dark:peer-focus:ring-green-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
      <span class="ml-2 dark:text-white">Include in Budget?</span>
    </label>
  </div>

  <div class="mb-6">
    <label class="relative inline-flex items-center cursor-pointer">
      <%= form.check_box :credit, { class: "sr-only peer" }, checked_value = "1", unchecked_value = "0"  %>
      <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-green-300 dark:peer-focus:ring-green-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-600"></div>
      <span class="ml-2 dark:text-white">Credit?</span>
    </label>
  </div>

  <div class="flex space-x-3 items-center justify-between">
    <%= submit_button form %>
    <%= cancel_button accounts_path %>
  </div>
<% end %>

app/views/accounts/_list.html.erb
<% @accounts.each do |account| %>
  <%= render account %>
<% end %>

app/views/accounts/_sidebar.html.erb
<% item_class = "flex text-2xl p-1" + (@all_accounts ? " bg-emerald-300 text-black rounded" : "") %>
<div>
  <%= link_to "All Accounts", transactions_path(account_id: 'all'), { class: item_class } %>
</div>
<% @accounts.each do |account| %>
  <% item_class = "flex pl-4 justify-between" + (@selected_account == account ? " bg-emerald-300 text-black rounded" : "") %>
  <div class="pb-2">
    <%= link_to transactions_path(account_id: account.id), { class: item_class } do %>
      <span><%= account.name %></span>
      <span><%= number_to_currency account.balance %></span>
    <% end %>
  </div>
<% end %>
<div class="flex justify-end">
  <%= link_to 'Add account', new_account_path, class: "font-medium text-right bg-transparent text-xs m-1 py-1 px-2 rounded-lg bg-emerald-500 hover:bg-emerald-800" %>
</div>

app/views/accounts/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl">

        <h1 id="modal-title" class="dark:text-slate-100">Edit account</h1>
        <%= render "form", account: @account %>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/index.html.erb
<div class="w-full">
  <% content_for :title, "Accounts" %>

  <div class="grid grid-cols-2 mb-4">
    <div class="text-left text-2xl font-bold pl-2 pt-2">Accounts</div>
    <div class="text-right pr-2 pt-2"><%= new_button new_account_path, "New" %></div>
  </div>

  <div id="accounts" class="tgrid-container">
    <div class="grid grid-cols-5 tgrid-header">
      <div>
        <strong class="tgrid-header-column">Name</strong>
      </div>
      <div>
        <strong class="tgrid-header-column">Type</strong>
      </div>
      <div>
        <strong class="tgrid-header-column">Budget?</strong>
      </div>
      <div>
        <strong class="tgrid-header-column">Credit?</strong>
      </div>
      <div>
        <strong class="tgrid-header-column">Action</strong>
      </div>
    </div>

    <% @accounts.each do |account| %>
      <%= render account %>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<%= turbo_frame_tag "model" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl">

        <h1 id="modal-title" class="dark:text-slate-100">New account</h1>
        <%= render "form", account: @account %>
      </div>
    </div>
  </div>
<% end %>